### PR TITLE
Fix issue #349

### LINKED ISSUE #349: Return of function set_line in history_change_line.c isn't caught.
There may be a malloc failure, if it fails, we do nothing.
```
		if (history_index_change_down(data->history) == FUNCT_SUCCESS)
			set_line(data, &data->line->line);
		else
```

### PR DESCRIPTION
**Pull request by jbrinksma**
## Description:

Shell now prints an error message and gives new prompt on history line allocation failure.
(Before this fix, it would have segfaulted.)

**Related issue (if applicable):** fixes #349

## Checklist:
  - [ ] The code change works
  - [ ] Passes all tests: `make test`
  - [ ] There is no commented out code in this PR.
  - [ ] `norminette srcs libft | grep -E "^Error" | wc -l` is not higher than master. If it is, run `norminette srcs libft | grep -E "^Error" -B 1` to see errors
  - [ ] I solemny swear my code is compliant with the [README][readme-file]

[readme-file]: https://github.com/OscarMulder/codam-42sh/blob/master/README.md

### CODE REVIEW

File: srcs/input_handling/input_read.c [hunk 1]
```diff
@@ -78,15 +78,21 @@ static int	input_parse(t_vshdata *data)
...
 		{
-			if (input_parse_char(data) == FUNCT_ERROR)
-				return (reset_input_read_return(data, FUNCT_ERROR));
+			if (input_parse_special(data) == FUNCT_FAILURE)
+			{
+				if (input_parse_char(data) == FUNCT_ERROR)
+					return (reset_input_read_return(data, FUNCT_ERROR));
+			}
 		}
+		else if (ret == FUNCT_ERROR)
```
Comment (thijsdejong) [inline srcs/input_handling/input_read.c]: This won't trigger if `input_parse_special` returns FUNCT_ERROR, is that correct?
