### PR TITLE
Properly manage expansions throughout execution of full command and fix error code

### LINKED ISSUE #381: Rework variable expansion from exec to fork
expected:
```
$> true; echo ${?}; false; echo ${?}
0
1
$>
```
us:
```
vsh 42sh > true; echo ${?}; false; echo ${?}
0
0
vsh 42sh > 
```

### LINKED ISSUE #416: Logical opperations fail if command not found
us:
```
vsh codam-42sh > peop=eoefk && sdjfkjsdlfkjsd || echo hoi && ls
vsh: sdjfkjsdlfkjsd: command not found.
```
bash, zsh and other shells:
```
bash-3.2$ peop=eoefk && sdjfkjsdlfkjsd || echo hoi && ls
bash: sdjfkjsdlfkjsd: command not found
hoi
42sh.dSYM       author          libft           test            vsh.dSYM
Dockerfile      fifo            objects         todo.md
Makefile        grammar         peop=eoefk      vsh
README.md       includes        srcs            vsh.1
```

### LINKED ISSUE #417: 'echo ${abc'  was giving leaks

### PR DESCRIPTION
**Pull request by jbrinksma**
## Description:

- Everything in a pipe sequence is now expanded right before execution of each individual process, instead of expanding everything before anything is executed.

- Exit code of binaries now work (using `WEXITSTATUS(status)` instead of just `status`)

**Related issue (if applicable):**
fixes #381
fixes #416 
fixes #417

## Checklist:
  - [x] The code change works
  - [x] Passes all tests: `make test`
  - [x] There is no commented out code in this PR.
  - [ ] `norminette srcs libft | grep -E "^Error" | wc -l` is not higher than master. If it is, run `norminette srcs libft | grep -E "^Error" -B 1` to see errors
  - [x] I solemny swear my code is compliant with the [README][readme-file]

[readme-file]: https://github.com/OscarMulder/codam-42sh/blob/master/README.md

### CODE REVIEW

**Comment by thijsdejong** [comment]
I have removed the comments on the `exit(1)` calls since we currently think it's acceptable to exit the shell if you can't fork or pipe.

File: srcs/exec/exec_create_process_args.c [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+
+#include "vsh.h"
+
+static size_t	count_args(t_ast *ast)
+{
+	t_ast	*probe;
+	size_t	i;
+
+	i = 0;
+	if (ast == NULL || ast->type != WORD)
```
Comment (marijnvanh) [inline srcs/exec/exec_create_process_args.c]: We might need to fix this in case the first ast node is an assign that is actually an executable. Will do in other branch.
